name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [macos-latest, windows-latest]

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build-prod

    - name: StreamDeck Distribution Tool
      uses: AdamCarballo/streamdeck-distribution-tool@v1
      with:
        input: dist/com.jordin.pomodoro.sdPlugin
        output: dist

    

    - name: Publish Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Release Build"
        files: |
          LICENSE.txt
          dist/com.jordin.pomodoro.sdPlugin
